repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    -   id: check-json
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
    -   id: flake8
    -   id: pretty-format-json
        args:
        -   --autofix
    -   id: trailing-whitespace
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    -   id: black
        language_version: python3.6
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: 'master'
    hooks:
    -   id: pylint
        args:
        -    --disable=C0103,E0401,R0205,R0903,W0511,W0703
